// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    [Index(nameof(AzureAdB2cobjectId), Name = "UI_ApplicationUser_AzureAdB2CObjectId", IsUnique = true)]
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            UserFeedback = new HashSet<UserFeedback>();
            UserInvitation = new HashSet<UserInvitation>();
            UserMessageFromApplicationUser = new HashSet<UserMessage>();
            UserMessageToApplicationUser = new HashSet<UserMessage>();
            UserProfile = new HashSet<UserProfile>();
        }

        [Key]
        public long ApplicationUserId { get; set; }
        [Required]
        [StringLength(150)]
        public string FullName { get; set; }
        [Required]
        [StringLength(150)]
        public string EmailAddress { get; set; }
        public DateTimeOffset LastLogIn { get; set; }
        [Column("AzureAdB2CObjectId")]
        public Guid AzureAdB2cobjectId { get; set; }
        [Column(TypeName = "money")]
        public decimal AvailableFunds { get; set; }

        [InverseProperty("ApplicationUser")]
        public virtual ApplicationUserRole ApplicationUserRole { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserFeedback> UserFeedback { get; set; }
        [InverseProperty("InvitingApplicationUser")]
        public virtual ICollection<UserInvitation> UserInvitation { get; set; }
        [InverseProperty(nameof(UserMessage.FromApplicationUser))]
        public virtual ICollection<UserMessage> UserMessageFromApplicationUser { get; set; }
        [InverseProperty(nameof(UserMessage.ToApplicationUser))]
        public virtual ICollection<UserMessage> UserMessageToApplicationUser { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}