// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class UserProfile
    {
        [Key]
        public long UserProfileId { get; set; }
        public long ApplicationUserId { get; set; }
        [Required]
        [StringLength(100)]
        public string About { get; set; }
        [Required]
        [StringLength(100)]
        public string Topics { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserProfile")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}